### ISSUE TITLE
student sounds a bit robotic

### ISSUE THREAD

**Issue by zuzana** [dhgrs/chainer-ClariNet#9]
Hi, 

I have trained both teacher/student networks. 
Teacher has very nice quality although it takes way too long to generate (1s takes ~6 minutes on gpu). 
Student results sound a bit robotic and have "noise" where should be silence. 
Do you have any tips on that? (I haven't changed any parameters besides path to trained teacher model).

UPDATE:
Here I my examples for 2 short (~1s) files: 
[clarinet-results.zip](https://github.com/dhgrs/chainer-ClariNet/files/2450048/clarinet-results.zip)

Thanks.

**Comment by zuzana** [comment]
ok, never mind for now, I'm making some mistake somewhere when generating with teacher, will update when I have it fixed.

**Comment by zuzana** [comment]
uploaded teacher and student results in a zip. 
warning: I had issues playing teacher with VLC, all other programs were fine - ffplay, itunes, audacity

**Comment by dhgrs** [comment]
I also get a bit noisy and robotic results from student network. It is hard to reproduce original ClariNet quality.
But I find that replacing
https://github.com/dhgrs/chainer-ClariNet/blob/71a3c8b443159aa008955d3a1538d82294852e22/StudentGaussianIAF/generate.py#L68

with 

```
output = means
```

makes the results better a bit. But noises in silence parts can not be removed.

Then I remove noise in silence parts manually. Here is a sample.

[RemoveNoiseManually.zip](https://github.com/dhgrs/chainer-ClariNet/files/2450644/RemoveNoiseManually.zip)

I feel that the quality is getting much better.

I think the cause is that I remove silences in preprocessing. It accelates training of voiced part, but makes the result a bit noisy.

Removing

https://github.com/dhgrs/chainer-ClariNet/blob/71a3c8b443159aa008955d3a1538d82294852e22/StudentGaussianIAF/utils.py#L27

might help training of silence parts. I want you to notice me the result if you try it.

**Comment by dhgrs** [comment]
Hi, I added these tips in develop branch and uploaded a generated sample.
https://nana-music.com/sounds/043ba7b4/
